### PR TITLE
feature/background_and_position - add features

### PR DESCRIPTION
**Pull request by ssomnoremac**
Not sure about usage of `background` as prop name.  Is `bg` better?

Does it make sense that positions are set in a counter-clockwise manner? I find that the most common position I set is top, left so `[5,15]` is the easiest for me. Of course margin and padding are clock-wise and that can't change. Is it confusing that position is different?

### CODE REVIEW

**Comment by ssomnoremac** [comment]
@tacomanator , i think I might still add the position prop from this PR before I do the next update. What do you think?

**Comment by tacomanator** [comment]
Position makes sense to me. For ease of use, how about having the vector mapping mirror the CSS box-edge property shorthand:

```
    1 or [1] => {top: 1, right: 1, bottom: 1, left: 1}
      [1, 2] => {top: 1, right: 2, bottom: 1, left: 2}
   [1, 2, 3] => {top: 1, right: 2, bottom: 3, left: 2}
[1, 2, 3, 4] => {top: 1, right: 2, bottom: 3, left: 4}
```

**Comment by ssomnoremac** [comment]
Yeah, that's interesting. I've never used box-edge but I'm down to aligning to something that already exists. I'll probably get to it this weekend. Feel free to implement before then if you'd like. Thanks for the support. Open to any other suggestions including on how to get more contributors 😄

**Comment by tacomanator** [comment]
:blush: I just meant the shorthand for properties that apply to the edges of boxes (i.e. the same way you have it for `margin` and `padding`). Sure, I don't mind taking a stab. As for contributors, just making it a great library is the best way that comes to mind.

**Comment by tacomanator** [comment]
Now that I've spent 5 minutes I realize my idea is dumb. Following same box-edge shorthand rules means always assigned a value to all four sides. Maybe that's why CSS position has no shorthand. Some alternatives?

### Expect 4 element array but allow empty/null

```jsx
    <Row position={[1]} />          // {top: 1}
    <Row position={[1, 2]} />       // {top: 1, right: 2}
    <Row position={[1, null, 2]} /> // {top: 1, bottom: 2}
    <Row position={[1, , , 2]} />   // {top: 1, left: 2}
    <Row position={[, , , 1]} />    // {left: 1}
```

Not particularly sexy. Error prone?

### Use object

```jsx
    <Row position={{top: 1, left: 2}} />
```

but then, why not just use `style={{top: 1, left: 2}}` directly?

### A clever analogy similar to 'dial'

Any ideas?

**Comment by ssomnoremac** [comment]
The way I see it the most common use cases are 
`top:10, left:10,` 
`top:0, left: 0, bottom: 0, right: 0`

That being said I think we should stick closer to what I had, and not overthink it. Position shouldn't be used too often anyway. Perhaps:

`position={0}` => `position: "absolute", top:0, left: 0, bottom: 0, right: 0`
`position={[0]}` => `position: "absolute", top:0`
`position={[10,10]}` => `position: "absolute", top:10, left:10`
`position={[0,1,0]}` => `position: "absolute", top:0, left:1, bottom:0`
`position={[null,null,0,0]}` => `position: "absolute", top:null, left:null, bottom:0, right:0`

I'll have to change the implementation a bit since position={0} is falsey, it will not work as is.

**Comment by tacomanator** [comment]
Seems to make the most sense. Personally I don't feel I use top/left more often than bottom/right, but then again I don't use position much.

**Pull request closed without merging**
